name: Link check

on:
  push:
    paths:
      - "README.md"
  pull_request:
    paths:
      - "README.md"

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress README.md
          fail: true
